FROM golang as builder

# Build Arguments
ARG build
ARG version

WORKDIR /src

COPY . /src

RUN   go mod download \
      && CGO_ENABLED=0 go build \
      -ldflags="-s -w -X main.Version=${version} -X main.Build=${build}" -o /grpcs ./cmd/grpc/server

FROM scratch
COPY --from=builder /grpcs /grpcs

EXPOSE 89

ENTRYPOINT ["./grpcs"]
